import * as express from "express";
import { RestApi, ServerSentEvent, UserCheck } from "./service";
export declare class Webserver {
    private port;
    private appname;
    private userCheck?;
    private app;
    private server;
    private log;
    private staticContent;
    private staticUrl;
    private faviconPath;
    private debug;
    private apis;
    private corsOptions;
    private tokentimeout;
    private authService;
    private sseUrl;
    private sse;
    private tokens;
    constructor(port: number, appname: string, userCheck?: UserCheck | undefined, log?: express.Handler);
    setStaticContent(path: string): void;
    setStaticUrl(url: string): void;
    setFaviconPath(path: string): void;
    setDebug(dbg: boolean): void;
    addApi(api: RestApi): void;
    setCorsOptions(opt: any): void;
    setSSE(url: string): void;
    getSSEurl(): string;
    getSSE(): ServerSentEvent;
    start(): void;
    private insertStandards;
    private insertStatic;
    private insertDebug;
    private insertSessionRouter;
    private insertAppRouters;
    private insertLast;
    private run;
    private authenticate;
    private login;
    private NTLMAuth;
    private formAuth;
    private noneAuth;
}
